/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

let keywords = [
  'COMPDEV',
  'TEXT',
  'WHERE',
  'LZ4',
  'BY',
  'DEVICE',
  'CACHE',
  'SNAPPY',
  'ENCODING',
  'LOSS',
  'ORDER',
  'KILL',
  'ADD',
  'TIMESERIES',
  'RENAME',
  'LIMIT',
  'DROP',
  'STORAGE',
  'GORILLA',
  'VALUES',
  'PATHS',
  'ALIGN',
  'USER',
  'GROUP',
  'CREATE',
  'SCHEMA',
  'TO',
  'LIST',
  'COMPRESSION',
  'COUNT',
  'DOUBLE',
  'FOR',
  'TIME',
  'OFFSET',
  'SLIMIT',
  'ATTRIBUTES',
  'TTL',
  'TAGS',
  'INTO',
  'AND',
  'OF',
  'SET',
  'LATEST',
  'BOOLEAN',
  'WITH',
  'UPSERT',
  'UNSET',
  'GZIP',
  'LAST',
  'VERSION',
  'ROLE',
  'AS',
  'PLAIN',
  'LEVEL',
  'QUERY',
  'INT32',
  'DESC',
  'FLOAT',
  'FLUSH',
  'NODES',
  'FULL',
  'UNCOMPRESSED',
  'FROM',
  'PROCESSLIST',
  'ASC',
  'GRANT',
  'INSERT',
  'LINEAR',
  'COMPRESSOR',
  'FILL',
  'COMPMINTIME',
  'ALIAS',
  'TIMESTAMP',
  'PASSWORD',
  'DISABLE',
  'DELETE',
  'DATATYPE',
  'COMPMAXTIME',
  'OR',
  'MERGE',
  'NOT',
  'SNAPSHOT',
  'PRIVILEGES',
  'DEVICES',
  'ON',
  'PREVIOUS',
  'RLE',
  'SDT',
  'CLEAR',
  'SELECT',
  'INT64',
  'ALTER',
  'ALL',
  'CHILD',
  'SHOW',
  'REVOKE',
  'REVOKE_USER_PRIVILEGE',
  'REVOKE_USER_ROLE',
  'LIST_USER',
  'DELETE_ROLE',
  'CREATE_TIMESERIES',
  'DELETE_USER',
  'GRANT_ROLE_PRIVILEGE',
  'CREATE_USER',
  'DROP_TRIGGER',
  'DROP_FUNCTION',
  'MODIFY_PASSWORD',
  'START_TRIGGER',
  'SET_STORAGE_GROUP',
  'GRANT_USER_PRIVILEGE',
  'CREATE_ROLE',
  'REVOKE_ROLE_PRIVILEGE',
  'TS_2DIFF',
  'CREATE_TRIGGER',
  'INSERT_TIMESERIES',
  'CREATE_FUNCTION',
  'LIST_ROLE',
  'READ_TIMESERIES',
  'GRANT_USER_ROLE',
  'DELETE_TIMESERIES',
  'STOP_TRIGGER',
];
export default keywords;
