const selectList = {
  SET: ['SET STORAGE GROUP TO <FullPath>', 'SET TTL TO <StorageGroupPath> <Integer>'],
  CREATE: ['CREATE TIMESERIES <FullPath> WITH <AttributeClauses>', 'CREATE TIMESERIES <FullPath> WITH <AttributeClauses> TAGS (<Clauses>) ATTRIBUTES(<Clauses>)'],
  ALTER: [
    'ALTER TIMESERIES <FullPath> ADD TAGS <Clauses>',
    'ALTER TIMESERIES <FullPath> ADD ATTRIBUTES <Clauses>',
    'ALTER TIMESERIES <FullPath> DROP <TagNames>',
    'ALTER TIMESERIES <FullPath> RENAME <OldName> TO <NewName>',
    'ALTER TIMESERIES <FullPath> SET <Clauses>',
    'ALTER TIMESERIES <FullPath>',
  ],
  DELETE: ['DELETE STORAGE GROUP <PrefixPath>', 'DELETE TIMESERIES <PrefixPath>', ' FROM <PrefixPath>', 'DELETE FROM <PrefixPath> WHERE <WhereClause>'],
  UNSET: ['UNSET TTL TO <StorageGroupPath>'],
  UPSERT: ['UPSERT ALIAS=<NewName> TAGS(<Clauses>) ATTRIBUTES(<Clauses>)'],
  SHOW: [
    'SHOW STORAGE GROUP',
    'SHOW STORAGE GROUP <PrefixPath>',
    'SHOW TIMESERIES',
    'SHOW TIMESERIES (<PrefixPath>)? Where <WhereClause>',
    'SHOW TIMESERIES (<PrefixPath>)? LIMIT <Integer> OFFSET <Integer>',
    'SHOW LATEST TIMESERIES (<PrefixPath>)?',
    'SHOW DEVICES <PrefixPath> WITH STORAGE GROUP',
    'SHOW ALL TTL',
    'SHOW TTL <StorageGroupNames>',
    'SHOW CHILD PATHS <prefixPath>',
    'SHOW CHILD NODES <prefixPath>',
    'SHOW DEVICES',
    'SHOW DEVICES <PrefixPath>',
    'SHOW DEVICES WITH STORAGE GROUP',
    'SHOW SHOW DEVICES <PrefixPath> WITH STORAGE GROUP',
  ],
  COUNT: ['COUNT TIMESERIES <Path> GROUP BY LEVEL=<Integer>', 'COUNT NODES <PrefixPath> LEVEL=<Integer>'],
  INSERT: ['INSERT INTO <PrefixPath>(TIMESTAMP, <PointNames>) VALUES(<Values>)'],
  SELECT: [
    'SELECT <SelectClause> FROM <FromClause>',
    'SELECT <SelectClause> FROM <FromClause> WHERE <WhereClause>',
    'SELECT <SelectClause> FROM <FromClause> WHERE <WhereClause> GROUP BY <GroupByTimeClause>',
    'SELECT <SelectClause> FROM <FromClause> WHERE <WhereClause> FILL <FillClause>',
  ],
  ORDER: ['ORDER BY TIME ASC | DESC'],
  LIMIT: ['LIMIT <Integer> [OFFSET <Integer>]?'],
  SLIMIT: ['SLIMIT <Integer> [OFFSET <Integer>]?'],
};
export default selectList;
